var v1 = 'string';
console.log(v1, '-', typeof(v1));
v1 = true;
console.log(v1, '-', typeof(v1));
v1 = 2;
console.log(v1, '-', typeof(v1));
v1 = undefined;
console.log(v1, '-', typeof(v1));
v1 = parseInt('teste');
console.log(v1, '-', typeof(v1));